name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security:
    name: Security checks
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: |
          if [ ! -d "lib/forge-std" ] || [ -z "$(ls -A lib/forge-std)" ]; then
            rm -rf lib/forge-std
            git submodule add https://github.com/foundry-rs/forge-std lib/forge-std
          fi
          if [ ! -d "lib/openzeppelin-contracts" ] || [ -z "$(ls -A lib/openzeppelin-contracts)" ]; then
            rm -rf lib/openzeppelin-contracts
            git submodule add https://github.com/OpenZeppelin/openzeppelin-contracts lib/openzeppelin-contracts
          fi
          git submodule update --init --recursive
        
      - name: Install Slither
        run: |
          pip3 install slither-analyzer
          pip3 install solc-select
          solc-select install 0.8.19
          solc-select use 0.8.19

      - name: Run Slither
        run: slither . --exclude-dependencies --exclude naming-convention --exclude external-function

      - name: Run Forge snapshot
        run: forge snapshot --check
        
      - name: Run Gas Report
        run: forge test --gas-report
        
  mythril:
    name: Mythril analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Mythril Security Analysis
        uses: docker://mythril/myth
        with:
          args: analyze src/*.sol --solc solc-0.8.19 --execution-timeout 300