name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Install Dependencies
        run: |
          if [ ! -d "lib/forge-std" ] || [ -z "$(ls -A lib/forge-std)" ]; then
            rm -rf lib/forge-std
            git submodule add https://github.com/foundry-rs/forge-std lib/forge-std
          fi
          if [ ! -d "lib/openzeppelin-contracts" ] || [ -z "$(ls -A lib/openzeppelin-contracts)" ]; then
            rm -rf lib/openzeppelin-contracts
            git submodule add https://github.com/OpenZeppelin/openzeppelin-contracts lib/openzeppelin-contracts
          fi
          git submodule update --init --recursive

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
